---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Create directory"
  file:
    path: ~/backend
    state: directory

- name: "Copy compiled backend"
  copy:
    src: artifact.tar.gz
    dest: "~/backend/artifact.tar.gz"

- name: Executing node
  shell: |
    tar -xzvf artifact.tar.gz
    echo "backend extracted"
    cd ~/backend
    npm install
    ls -al
    pm2 stop default
    pm2 start npm -- start
    register: out_exec_node

- name: debug message
  debug: 
    # var=out.stdout_lines
    msg: "{{ out_exec_node.stdout_lines }}"
  