---

- name: Setup check1
  shell: |
    cd ~/
    echo "Root contents:"
    pwd
    ls -al
    cd ~/backend
    echo "Backend contents:"
    pwd
    ls -al
    echo "TYPEORM_DATABASE=${TYPEORM_DATABASE}"
    find ~/ -type f -name "artifact.tar.gz"
  register: out_setup_check1_node

- name: Setup check1 debug message
  debug: 
    msg: "{{ out_setup_check1_node.stdout_lines }}"

- name: "Create directory"
  file:
    path: ~/backend
    state: directory

- name: "Copy and unzip compiled backend"
  unarchive:
    src: artifact.tar.gz
    dest: "~/backend/"

- name: Setup check2
  shell: |
    cd ~/backend
    echo "Backend contents:"
    pwd
    ls -al
    rm -f ~/.npm/_logs/*
  register: out_setup_check2_node

- name: Setup check2 debug message
  debug: 
    msg: "{{ out_setup_check2_node.stdout_lines }}"
  
- name: Executing node
  shell: |
    cd ~/backend
    echo "Backend contents:"
    ls -al
    npm install
    npm run build
    pm2 stop default
    rm -f ~/.npm/_logs/*
    #npm run start &
    pm2 start npm -- start
    tail -n 100 ~/.npm/_logs/*
    echo "TYPEORM_DATABASE=${TYPEORM_DATABASE}"
  register: out_exec_node

- name: Execution debug message
  debug: 
    # var=out.stdout_lines
    msg: "{{ out_exec_node.stdout_lines }}"
  