---
- name: Cleansetup
  shell: |
    rm -rf ~/backend

- name: "Create directory"
  file:
    path: ~/backend
    state: directory

- name: "Copy and unzip compiled backend"
  unarchive:
    src: artifact.tar.gz
    dest: "~/backend/"

- name: Executing node
  shell: |
    cd ~/backend
    echo "Backend contents:"
    ls -al
    npm install
    npm run build
    pm2 stop default
    rm -f ~/.npm/_logs/*
    #npm run start &
    pm2 start npm -- start
    tail -n 100 ~/.npm/_logs/*
    echo "TYPEORM_DATABASE=$TYPEORM_DATABASE"
  register: out_exec_node

- name: debug message
  debug: 
    # var=out.stdout_lines
    msg: "{{ out_exec_node.stdout_lines }}"
  