---

- name: Setup check1
  shell: |
    cd ~/
    echo "Root contents:"
    pwd
    ls -al
    cd ~/.ansible
    echo ".ansible contents:"
    pwd
    ls -al
    echo "TYPEORM_DATABASE=${TYPEORM_DATABASE}"
    echo "Finding artifact.tar.gz ..."
    find ~/ -type f -name "artifact.tar.gz"
    echo "--done ..."
  register: out_setup_check1_node

- name: Setup check1 debug message
  debug: 
    msg: "{{ out_setup_check1_node.stdout_lines }}"

- name: "Create directory"
  file:
    path: ~/backend
    state: directory

- name: "Copy compiled backend artifact"
  copy:
    src: artifact.tar.gz
    dest: ~/backend/.

- name: "Untar artifact"
  shell: |
    cd ~/backend
    tar -xzf artifact.tar.gz 
    rm -f artifact.tar.gz
    echo "Backend contents:"
    pwd
    ls -al
    rm -f ~/.npm/_logs/*
  register: out_setup_check2_node

- name: untar debug message
  debug: 
    msg: "{{ out_setup_check2_node.stdout_lines }}"
  
- name: Executing node
  shell: |
    cd ~/backend
    echo "Backend contents:"
    ls -al
    npm install
    npm run build
    #pm2 stop default
    #npm run start &
    # pm2 start main.js
    pm2 start npm -- start
  register: out_exec_node

- name: Execution debug message
  debug: 
    # var=out.stdout_lines
    msg: "{{ out_exec_node.stdout_lines }}"
  